//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanDongHo.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.Serialization;

    public partial class ChiTietDongHo
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string ThuongHieu { get; set; }
        public string XuatXu { get; set; }
        public string GioiTinh { get; set; }
        public string Anh { get; set; }
        public int Gia { get; set; }
        public string chatLieuMat { get; set; }
        public Nullable<double> duongKinhMat { get; set; }
        public string chatLieuDay { get; set; }
        public Nullable<double> sizeDay { get; set; }
        public string chatLieuVo { get; set; }
        public Nullable<double> duongKinhVo { get; set; }
        public Nullable<double> timeBaoHanh { get; set; }
        public bool active { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tThuongHieu tThuongHieu { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tXuatXu tXuatXu { get; set; }
    }

    public enum ThuongHieu
    {
        Sonata,
        Fossil,
        Casio,
        Titan,
        Fastrack,
        Omax,
        Sports
    }

    public enum XuatSu
    {
        Italy,
        France,
        [field: Description("Việt Nam")]
        VietNam,
        Japan,
        Switzerland,
        Germany,
        [field: Description("Mỹ")]
        USA
    }
    public enum GioiTinh
    {
        Nam,
        Nu
    }
}
