//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tXuatXu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tXuatXu()
        {
            this.ChiTietDongHoes = new HashSet<ChiTietDongHo>();
        }
    
        public string XuatXu { get; set; }
        public string TenXuatXu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDongHo> ChiTietDongHoes { get; set; }
    }
}
